# hosts.yaml

all:

  vars:
    ansible_user: ansible

  children:

    db-servers:
      hosts:
        app1-db:
          ansible_host:  10.0.0.1
          db_port: 3306
          db_user: db_user1
          db_pass: db_pass1
          db_database: app1-db
        app2-db:
          ansible_host: 10.0.0.2
          db_port: 3306
          db_user: db_user1
          db_pass: db_pass1
          db_database: app2-db
